package main

import (
	"fmt"
	"math"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	shadowrocketDefaultTestURL  = "http://www.gstatic.com/generate_204"
	shadowrocketDefaultInterval = "600"
)

type clashSubscriptionConfig struct {
	Proxies     []map[string]any        `yaml:"proxies"`
	ProxyGroups []clashProxyGroupConfig `yaml:"proxy-groups"`
	Rules       []string                `yaml:"rules"`
}

type clashProxyGroupConfig struct {
	Name      string   `yaml:"name"`
	Type      string   `yaml:"type"`
	Proxies   []string `yaml:"proxies"`
	URL       any      `yaml:"url"`
	Interval  any      `yaml:"interval"`
	Timeout   any      `yaml:"timeout"`
	Tolerance any      `yaml:"tolerance"`
}

type shadowrocketGroupCandidate struct {
	name      string
	groupType string
	members   []shadowrocketGroupMember
	params    []string
}

type shadowrocketGroupMember struct {
	name    string
	isGroup bool
}

// ConvertClashYAMLToShadowrocket 将最终 Clash YAML 转换为 Shadowrocket 配置文件。
func ConvertClashYAMLToShadowrocket(yamlContent string) (string, error) {
	var cfg clashSubscriptionConfig
	if err := yaml.Unmarshal([]byte(yamlContent), &cfg); err != nil {
		return "", fmt.Errorf("解析 Clash YAML 失败: %w", err)
	}
	if len(cfg.Proxies) == 0 {
		return "", fmt.Errorf("未找到可转换的 proxies 节点")
	}

	usedNames := make(map[string]bool)
	proxyNameMap := make(map[string]string)
	var proxyLines []string
	var proxyNames []string

	for _, proxy := range cfg.Proxies {
		if !isShadowrocketSupportedProxy(proxy) {
			continue
		}
		rawName := valueAsString(proxy["name"])
		safeName := uniqueShadowrocketName(rawName, usedNames)
		line, ok := shadowrocketProxyLine(safeName, proxy)
		if !ok {
			delete(usedNames, safeName)
			continue
		}
		proxyNameMap[rawName] = safeName
		proxyNames = append(proxyNames, safeName)
		proxyLines = append(proxyLines, line)
	}

	if len(proxyLines) == 0 {
		return "", fmt.Errorf("未找到 Shadowrocket 支持的可用代理节点")
	}

	groupNameMap := make(map[string]string)
	for _, group := range cfg.ProxyGroups {
		if strings.TrimSpace(group.Name) == "" {
			continue
		}
		groupNameMap[group.Name] = uniqueShadowrocketName(group.Name, usedNames)
	}

	groupLines, emittedGroups, firstPolicy := shadowrocketProxyGroupLines(cfg.ProxyGroups, proxyNameMap, groupNameMap, proxyNames, usedNames)
	ruleLines := shadowrocketRuleLines(cfg.Rules, proxyNameMap, groupNameMap, emittedGroups, firstPolicy)

	var b strings.Builder
	b.WriteString("# Generated by ClashSubAST for Shadowrocket\n\n")
	b.WriteString("[General]\n")
	b.WriteString("bypass-system = true\n")
	b.WriteString("skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local\n\n")

	b.WriteString("[Proxy]\n")
	b.WriteString(strings.Join(proxyLines, "\n"))
	b.WriteString("\n\n")

	b.WriteString("[Proxy Group]\n")
	b.WriteString(strings.Join(groupLines, "\n"))
	b.WriteString("\n\n")

	b.WriteString("[Rule]\n")
	b.WriteString(strings.Join(ruleLines, "\n"))
	b.WriteString("\n")

	return b.String(), nil
}

func isShadowrocketSupportedProxy(proxy map[string]any) bool {
	switch strings.ToLower(valueAsString(proxy["type"])) {
	case "ss", "socks5", "socks", "vless", "hysteria2", "hy2":
		return true
	default:
		return false
	}
}

func shadowrocketProxyLine(name string, proxy map[string]any) (string, bool) {
	proxyType := strings.ToLower(valueAsString(proxy["type"]))
	server := valueAsString(proxy["server"])
	port := valueAsString(proxy["port"])
	if server == "" || port == "" {
		return "", false
	}

	switch proxyType {
	case "ss":
		cipher := firstNonEmpty(valueAsString(proxy["cipher"]), valueAsString(proxy["method"]))
		password := valueAsString(proxy["password"])
		if cipher == "" || password == "" {
			return "", false
		}
		return joinShadowrocketLine(name, "ss", server, port, "password="+cleanShadowrocketValue(password), "method="+cleanShadowrocketValue(cipher), "udp-relay=true"), true
	case "socks", "socks5":
		parts := []string{name + " = socks5", cleanShadowrocketValue(server), cleanShadowrocketValue(port)}
		username := valueAsString(proxy["username"])
		password := valueAsString(proxy["password"])
		if username != "" || password != "" {
			parts = append(parts, cleanShadowrocketValue(username), cleanShadowrocketValue(password))
		}
		return strings.Join(parts, ","), true
	case "vless":
		uuid := firstNonEmpty(valueAsString(proxy["uuid"]), valueAsString(proxy["password"]))
		if uuid == "" {
			return "", false
		}
		params := []string{"password=" + cleanShadowrocketValue(uuid)}
		if truthy(proxy["tls"]) {
			params = append(params, "tls=true")
		}
		if sni := firstNonEmpty(valueAsString(proxy["servername"]), valueAsString(proxy["sni"])); sni != "" {
			params = append(params, "peer="+cleanShadowrocketValue(sni))
		}
		if truthy(proxy["skip-cert-verify"]) {
			params = append(params, "allowInsecure=1")
		}
		if flow := valueAsString(proxy["flow"]); flow != "" {
			params = append(params, "flow="+cleanShadowrocketValue(flow))
		}
		params = append(params, vlessTransportParams(proxy)...)
		return joinShadowrocketLine(name, "vless", server, port, params...), true
	case "hysteria2", "hy2":
		auth := firstNonEmpty(valueAsString(proxy["password"]), valueAsString(proxy["auth"]))
		if auth == "" {
			return "", false
		}
		params := []string{"auth=" + cleanShadowrocketValue(auth), "udp=1"}
		if sni := firstNonEmpty(valueAsString(proxy["sni"]), valueAsString(proxy["servername"])); sni != "" {
			params = append(params, "peer="+cleanShadowrocketValue(sni))
		}
		if obfsPassword := firstNonEmpty(valueAsString(proxy["obfs-password"]), valueAsString(proxy["obfsParam"])); obfsPassword != "" {
			params = append(params, "obfsParam="+cleanShadowrocketValue(obfsPassword))
		}
		if alpn := firstListValue(proxy["alpn"]); alpn != "" {
			params = append(params, "alpn="+cleanShadowrocketValue(alpn))
		}
		if truthy(proxy["skip-cert-verify"]) {
			params = append(params, "allowInsecure=1")
		}
		return joinShadowrocketLine(name, "hysteria2", server, port, params...), true
	default:
		return "", false
	}
}

func vlessTransportParams(proxy map[string]any) []string {
	network := strings.ToLower(valueAsString(proxy["network"]))
	switch network {
	case "ws":
		params := []string{"obfs=websocket"}
		if wsOpts, ok := valueAsMap(proxy["ws-opts"]); ok {
			if path := valueAsString(wsOpts["path"]); path != "" {
				params = append(params, "obfs-uri="+cleanShadowrocketValue(path))
			}
			if headers, ok := valueAsMap(wsOpts["headers"]); ok {
				if host := valueAsString(headers["Host"]); host != "" {
					params = append(params, "obfs-host="+cleanShadowrocketValue(host))
				}
			}
		}
		return params
	case "grpc":
		params := []string{"obfs=grpc"}
		if grpcOpts, ok := valueAsMap(proxy["grpc-opts"]); ok {
			if serviceName := valueAsString(grpcOpts["grpc-service-name"]); serviceName != "" {
				params = append(params, "serviceName="+cleanShadowrocketValue(serviceName))
			}
		}
		return params
	default:
		return nil
	}
}

func shadowrocketProxyGroupLines(groups []clashProxyGroupConfig, proxyNameMap, groupNameMap map[string]string, proxyNames []string, usedNames map[string]bool) ([]string, map[string]bool, string) {
	candidates := make(map[string]shadowrocketGroupCandidate)
	var order []string

	for _, group := range groups {
		safeName, ok := groupNameMap[group.Name]
		if !ok {
			continue
		}
		candidate := shadowrocketGroupCandidate{
			name:      safeName,
			groupType: mapShadowrocketGroupType(group.Type),
			params:    shadowrocketGroupParams(group),
		}

		seenMembers := make(map[string]bool)
		for _, rawMember := range group.Proxies {
			member := strings.TrimSpace(rawMember)
			if member == "" {
				continue
			}
			if safeProxy, ok := proxyNameMap[member]; ok {
				appendUniqueGroupMember(&candidate, shadowrocketGroupMember{name: safeProxy}, seenMembers)
				continue
			}
			if safeGroup, ok := groupNameMap[member]; ok {
				appendUniqueGroupMember(&candidate, shadowrocketGroupMember{name: safeGroup, isGroup: true}, seenMembers)
				continue
			}
			if builtInPolicy, ok := shadowrocketBuiltInPolicy(member); ok {
				appendUniqueGroupMember(&candidate, shadowrocketGroupMember{name: builtInPolicy}, seenMembers)
			}
		}

		candidates[safeName] = candidate
		order = append(order, safeName)
	}

	validCache := make(map[string]bool)
	visiting := make(map[string]bool)
	var isValidGroup func(string) bool
	isValidGroup = func(name string) bool {
		if cached, ok := validCache[name]; ok {
			return cached
		}
		if visiting[name] {
			return false
		}
		candidate, ok := candidates[name]
		if !ok {
			return false
		}
		visiting[name] = true
		defer delete(visiting, name)

		for _, member := range candidate.members {
			if !member.isGroup || isValidGroup(member.name) {
				validCache[name] = true
				return true
			}
		}
		validCache[name] = false
		return false
	}

	emittedGroups := make(map[string]bool)
	var lines []string
	firstPolicy := ""

	for _, name := range order {
		if !isValidGroup(name) {
			continue
		}
		candidate := candidates[name]
		var members []string
		seenMembers := make(map[string]bool)
		for _, member := range candidate.members {
			if member.isGroup && !isValidGroup(member.name) {
				continue
			}
			if seenMembers[member.name] {
				continue
			}
			seenMembers[member.name] = true
			members = append(members, member.name)
		}
		if len(members) == 0 {
			continue
		}

		lineParts := append([]string{candidate.name + " = " + candidate.groupType}, members...)
		lineParts = append(lineParts, candidate.params...)
		lines = append(lines, strings.Join(lineParts, ","))
		emittedGroups[candidate.name] = true
		if firstPolicy == "" {
			firstPolicy = candidate.name
		}
	}

	if len(lines) == 0 {
		defaultGroupName := uniqueShadowrocketName("PROXY", usedNames)
		lineParts := append([]string{defaultGroupName + " = select"}, proxyNames...)
		lines = append(lines, strings.Join(lineParts, ","))
		emittedGroups[defaultGroupName] = true
		firstPolicy = defaultGroupName
	}

	return lines, emittedGroups, firstPolicy
}

func appendUniqueGroupMember(candidate *shadowrocketGroupCandidate, member shadowrocketGroupMember, seen map[string]bool) {
	if seen[member.name] {
		return
	}
	seen[member.name] = true
	candidate.members = append(candidate.members, member)
}

func mapShadowrocketGroupType(groupType string) string {
	switch strings.ToLower(strings.TrimSpace(groupType)) {
	case "url-test", "fallback", "load-balance", "random":
		return strings.ToLower(strings.TrimSpace(groupType))
	default:
		return "select"
	}
}

func shadowrocketGroupParams(group clashProxyGroupConfig) []string {
	groupType := mapShadowrocketGroupType(group.Type)
	if groupType == "select" {
		return nil
	}

	url := firstNonEmpty(valueAsString(group.URL), shadowrocketDefaultTestURL)
	interval := firstNonEmpty(valueAsString(group.Interval), shadowrocketDefaultInterval)
	params := []string{"url=" + cleanShadowrocketValue(url), "interval=" + cleanShadowrocketValue(interval)}
	if timeout := valueAsString(group.Timeout); timeout != "" {
		params = append(params, "timeout="+cleanShadowrocketValue(timeout))
	}
	if tolerance := valueAsString(group.Tolerance); tolerance != "" {
		params = append(params, "tolerance="+cleanShadowrocketValue(tolerance))
	}
	return params
}

func shadowrocketRuleLines(rules []string, proxyNameMap, groupNameMap map[string]string, emittedGroups map[string]bool, fallbackPolicy string) []string {
	var lines []string
	for _, rawRule := range rules {
		line, ok := shadowrocketRuleLine(rawRule, proxyNameMap, groupNameMap, emittedGroups)
		if ok {
			lines = append(lines, line)
		}
	}

	if len(lines) == 0 {
		lines = append(lines, "FINAL,"+fallbackPolicy)
	}
	return lines
}

func shadowrocketRuleLine(rawRule string, proxyNameMap, groupNameMap map[string]string, emittedGroups map[string]bool) (string, bool) {
	rule := strings.TrimSpace(rawRule)
	if rule == "" || strings.HasPrefix(rule, "#") {
		return "", false
	}

	parts := strings.Split(rule, ",")
	for i := range parts {
		parts[i] = strings.TrimSpace(parts[i])
	}
	if len(parts) < 2 {
		return "", false
	}

	ruleType := strings.ToUpper(parts[0])
	if ruleType == "MATCH" {
		target := strings.Join(parts[1:], ",")
		return "FINAL," + mapShadowrocketPolicy(target, proxyNameMap, groupNameMap, emittedGroups), true
	}

	targetStart := 2
	if len(parts) <= targetStart {
		return "", false
	}

	targetEnd := len(parts) - 1
	suffix := ""
	if strings.EqualFold(parts[targetEnd], "no-resolve") {
		suffix = parts[targetEnd]
		targetEnd--
	}
	if targetEnd < targetStart {
		return "", false
	}

	prefix := append([]string{}, parts[:targetStart]...)
	target := strings.Join(parts[targetStart:targetEnd+1], ",")
	converted := append(prefix, mapShadowrocketPolicy(target, proxyNameMap, groupNameMap, emittedGroups))
	if suffix != "" {
		converted = append(converted, suffix)
	}
	return strings.Join(converted, ","), true
}

func mapShadowrocketPolicy(policy string, proxyNameMap, groupNameMap map[string]string, emittedGroups map[string]bool) string {
	policy = strings.TrimSpace(policy)
	if safeGroup, ok := groupNameMap[policy]; ok && emittedGroups[safeGroup] {
		return safeGroup
	}
	if safeProxy, ok := proxyNameMap[policy]; ok {
		return safeProxy
	}
	if builtInPolicy, ok := shadowrocketBuiltInPolicy(policy); ok {
		return builtInPolicy
	}
	return sanitizeShadowrocketName(policy)
}

func shadowrocketBuiltInPolicy(policy string) (string, bool) {
	upper := strings.ToUpper(strings.TrimSpace(policy))
	switch upper {
	case "DIRECT", "REJECT", "REJECT-DROP", "REJECT-TINYGIF", "PROXY":
		return upper, true
	default:
		return "", false
	}
}

func joinShadowrocketLine(name, proxyType, server, port string, params ...string) string {
	parts := []string{name + " = " + proxyType, cleanShadowrocketValue(server), cleanShadowrocketValue(port)}
	parts = append(parts, params...)
	return strings.Join(parts, ",")
}

func uniqueShadowrocketName(rawName string, used map[string]bool) string {
	name := sanitizeShadowrocketName(rawName)
	if name == "" {
		name = "Proxy"
	}
	base := name
	for i := 2; used[name]; i++ {
		name = fmt.Sprintf("%s %d", base, i)
	}
	used[name] = true
	return name
}

func sanitizeShadowrocketName(name string) string {
	replacer := strings.NewReplacer(
		",", "，",
		"\r", " ",
		"\n", " ",
		"=", "-",
	)
	return strings.TrimSpace(replacer.Replace(name))
}

func cleanShadowrocketValue(value string) string {
	replacer := strings.NewReplacer("\r", " ", "\n", " ")
	return strings.TrimSpace(replacer.Replace(value))
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return strings.TrimSpace(value)
		}
	}
	return ""
}

func truthy(value any) bool {
	switch v := value.(type) {
	case bool:
		return v
	case string:
		v = strings.TrimSpace(strings.ToLower(v))
		return v == "true" || v == "1" || v == "yes"
	case int:
		return v != 0
	case int64:
		return v != 0
	case float64:
		return v != 0
	default:
		return false
	}
}

func valueAsString(value any) string {
	switch v := value.(type) {
	case nil:
		return ""
	case string:
		return strings.TrimSpace(v)
	case bool:
		return strconv.FormatBool(v)
	case int:
		return strconv.Itoa(v)
	case int64:
		return strconv.FormatInt(v, 10)
	case uint:
		return strconv.FormatUint(uint64(v), 10)
	case uint64:
		return strconv.FormatUint(v, 10)
	case float64:
		if math.Trunc(v) == v {
			return strconv.FormatInt(int64(v), 10)
		}
		return strconv.FormatFloat(v, 'f', -1, 64)
	case float32:
		f := float64(v)
		if math.Trunc(f) == f {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		return strings.TrimSpace(fmt.Sprint(v))
	}
}

func valueAsMap(value any) (map[string]any, bool) {
	switch v := value.(type) {
	case map[string]any:
		return v, true
	case map[any]any:
		out := make(map[string]any, len(v))
		for key, value := range v {
			out[fmt.Sprint(key)] = value
		}
		return out, true
	default:
		return nil, false
	}
}

func firstListValue(value any) string {
	switch v := value.(type) {
	case []any:
		for _, item := range v {
			if itemValue := valueAsString(item); itemValue != "" {
				return itemValue
			}
		}
	case []string:
		for _, item := range v {
			if strings.TrimSpace(item) != "" {
				return strings.TrimSpace(item)
			}
		}
	default:
		return valueAsString(value)
	}
	return ""
}
