package main

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	surgeDefaultTestURL  = "http://www.gstatic.com/generate_204"
	surgeDefaultInterval = "600"
)

type surgeTargetVersion string

const (
	surgeTargetLatest surgeTargetVersion = "latest"
	surgeTarget576    surgeTargetVersion = "5.7.6"
)

type surgeGroupCandidate struct {
	name      string
	groupType string
	members   []surgeGroupMember
	params    []string
}

type surgeGroupMember struct {
	name    string
	isGroup bool
}

// ConvertClashYAMLToSurge 将最终 Clash YAML 转换为 Surge 5 配置文件。
func ConvertClashYAMLToSurge(yamlContent string) (string, error) {
	return convertClashYAMLToSurge(yamlContent, surgeTargetLatest)
}

// ConvertClashYAMLToSurge576 将最终 Clash YAML 转换为 Surge Mac 5.7.6 兼容配置文件。
func ConvertClashYAMLToSurge576(yamlContent string) (string, error) {
	return convertClashYAMLToSurge(yamlContent, surgeTarget576)
}

func convertClashYAMLToSurge(yamlContent string, target surgeTargetVersion) (string, error) {
	var cfg clashSubscriptionConfig
	if err := yaml.Unmarshal([]byte(yamlContent), &cfg); err != nil {
		return "", fmt.Errorf("解析 Clash YAML 失败: %w", err)
	}
	if len(cfg.Proxies) == 0 {
		return "", fmt.Errorf("未找到可转换的 proxies 节点")
	}

	usedNames := make(map[string]bool)
	proxyNameMap := make(map[string]string)
	var proxyLines []string
	var proxyNames []string

	for _, proxy := range cfg.Proxies {
		if !isSurgeSupportedProxy(proxy) {
			continue
		}
		rawName := valueAsString(proxy["name"])
		safeName := uniqueSurgeName(rawName, usedNames)
		line, ok := surgeProxyLine(safeName, proxy, target)
		if !ok {
			delete(usedNames, safeName)
			continue
		}
		proxyNameMap[rawName] = safeName
		proxyNames = append(proxyNames, safeName)
		proxyLines = append(proxyLines, line)
	}

	if len(proxyLines) == 0 {
		return "", fmt.Errorf("未找到 Surge 5 支持的可用代理节点")
	}

	groupNameMap := make(map[string]string)
	for _, group := range cfg.ProxyGroups {
		if strings.TrimSpace(group.Name) == "" {
			continue
		}
		groupNameMap[group.Name] = uniqueSurgeName(group.Name, usedNames)
	}

	groupLines, emittedGroups, firstPolicy := surgeProxyGroupLines(cfg.ProxyGroups, proxyNameMap, groupNameMap, proxyNames, usedNames)
	ruleLines := surgeRuleLines(cfg.Rules, proxyNameMap, groupNameMap, emittedGroups, firstPolicy)

	var b strings.Builder
	b.WriteString("# Generated by Clash Subscription Decoder for " + surgeConfigLabel(target) + "\n\n")
	b.WriteString("[General]\n")
	b.WriteString("skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.1, localhost, *.local\n\n")

	b.WriteString("[Proxy]\n")
	b.WriteString(strings.Join(proxyLines, "\n"))
	b.WriteString("\n\n")

	b.WriteString("[Proxy Group]\n")
	b.WriteString(strings.Join(groupLines, "\n"))
	b.WriteString("\n\n")

	b.WriteString("[Rule]\n")
	b.WriteString(strings.Join(ruleLines, "\n"))
	b.WriteString("\n")

	return b.String(), nil
}

func surgeConfigLabel(target surgeTargetVersion) string {
	if target == surgeTarget576 {
		return "Surge 5.7.6"
	}
	return "Surge Latest"
}

func isSurgeSupportedProxy(proxy map[string]any) bool {
	switch strings.ToLower(valueAsString(proxy["type"])) {
	case "ss", "socks5", "socks", "vmess", "trojan", "hysteria2", "hy2":
		return true
	default:
		return false
	}
}

func surgeProxyLine(name string, proxy map[string]any, target surgeTargetVersion) (string, bool) {
	proxyType := strings.ToLower(valueAsString(proxy["type"]))
	server := valueAsString(proxy["server"])
	port := valueAsString(proxy["port"])
	if server == "" || port == "" {
		return "", false
	}

	switch proxyType {
	case "ss":
		cipher := firstNonEmpty(valueAsString(proxy["cipher"]), valueAsString(proxy["method"]))
		password := valueAsString(proxy["password"])
		if cipher == "" || password == "" {
			return "", false
		}
		if target == surgeTarget576 && isSurgeSS2022Cipher(cipher) {
			return "", false
		}
		return joinSurgeLine(name, "ss", server, port, "encrypt-method="+cleanSurgeValue(cipher), "password="+cleanSurgeValue(password), "udp-relay=true"), true
	case "socks", "socks5":
		parts := []string{name + " = socks5", cleanSurgeValue(server), cleanSurgeValue(port)}
		username := valueAsString(proxy["username"])
		password := valueAsString(proxy["password"])
		if username != "" || password != "" {
			parts = append(parts, cleanSurgeValue(username), cleanSurgeValue(password))
		}
		parts = append(parts, "udp-relay=true")
		return strings.Join(parts, ","), true
	case "vmess":
		uuid := firstNonEmpty(valueAsString(proxy["uuid"]), valueAsString(proxy["username"]), valueAsString(proxy["password"]))
		if uuid == "" {
			return "", false
		}
		params := []string{"username=" + cleanSurgeValue(uuid)}
		if cipher := firstNonEmpty(valueAsString(proxy["cipher"]), valueAsString(proxy["encrypt-method"])); cipher != "" && cipher != "auto" {
			params = append(params, "encrypt-method="+cleanSurgeValue(cipher))
		}
		if truthy(proxy["tls"]) {
			params = append(params, "tls=true")
		}
		params = append(params, surgeTLSParams(proxy)...)
		params = append(params, surgeTransportParams(proxy)...)
		return joinSurgeLine(name, "vmess", server, port, params...), true
	case "trojan":
		password := valueAsString(proxy["password"])
		if password == "" {
			return "", false
		}
		params := []string{"password=" + cleanSurgeValue(password), "udp-relay=true"}
		params = append(params, surgeTLSParams(proxy)...)
		params = append(params, surgeTransportParams(proxy)...)
		return joinSurgeLine(name, "trojan", server, port, params...), true
	case "hysteria2", "hy2":
		password := firstNonEmpty(valueAsString(proxy["password"]), valueAsString(proxy["auth"]))
		if password == "" {
			return "", false
		}
		if target == surgeTarget576 && hasHysteria2SalamanderObfs(proxy) {
			return "", false
		}
		params := []string{"password=" + cleanSurgeValue(password)}
		if bandwidth := firstNonEmpty(valueAsString(proxy["download-bandwidth"]), valueAsString(proxy["down"]), valueAsString(proxy["down-mbps"])); bandwidth != "" {
			params = append(params, "download-bandwidth="+cleanSurgeValue(bandwidth))
		}
		if obfsPassword := firstNonEmpty(valueAsString(proxy["obfs-password"]), valueAsString(proxy["obfsParam"])); obfsPassword != "" {
			params = append(params, "salamander-password="+cleanSurgeValue(obfsPassword))
		}
		if alpn := firstListValue(proxy["alpn"]); alpn != "" {
			params = append(params, "alpn="+cleanSurgeValue(alpn))
		}
		params = append(params, surgeTLSParams(proxy)...)
		return joinSurgeLine(name, "hysteria2", server, port, params...), true
	default:
		return "", false
	}
}

func isSurgeSS2022Cipher(cipher string) bool {
	normalized := strings.ToLower(strings.TrimSpace(cipher))
	return strings.HasPrefix(normalized, "2022-")
}

func hasHysteria2SalamanderObfs(proxy map[string]any) bool {
	if firstNonEmpty(valueAsString(proxy["obfs-password"]), valueAsString(proxy["obfsParam"])) != "" {
		return true
	}
	return strings.EqualFold(strings.TrimSpace(valueAsString(proxy["obfs"])), "salamander")
}

func surgeTLSParams(proxy map[string]any) []string {
	var params []string
	if sni := firstNonEmpty(valueAsString(proxy["servername"]), valueAsString(proxy["sni"])); sni != "" {
		params = append(params, "sni="+cleanSurgeValue(sni))
	}
	if truthy(proxy["skip-cert-verify"]) {
		params = append(params, "skip-cert-verify=true")
	}
	return params
}

func surgeTransportParams(proxy map[string]any) []string {
	network := strings.ToLower(valueAsString(proxy["network"]))
	if network != "ws" {
		return nil
	}

	params := []string{"ws=true"}
	if wsOpts, ok := valueAsMap(proxy["ws-opts"]); ok {
		if path := valueAsString(wsOpts["path"]); path != "" {
			params = append(params, "ws-path="+cleanSurgeValue(path))
		}
		if headers, ok := valueAsMap(wsOpts["headers"]); ok {
			if headerLine := surgeWSHeaders(headers); headerLine != "" {
				params = append(params, "ws-headers="+headerLine)
			}
		}
	}
	return params
}

func surgeWSHeaders(headers map[string]any) string {
	var parts []string
	for key, value := range headers {
		key = cleanSurgeValue(key)
		headerValue := cleanSurgeValue(valueAsString(value))
		if key == "" || headerValue == "" {
			continue
		}
		parts = append(parts, key+":"+headerValue)
	}
	return strings.Join(parts, "|")
}

func surgeProxyGroupLines(groups []clashProxyGroupConfig, proxyNameMap, groupNameMap map[string]string, proxyNames []string, usedNames map[string]bool) ([]string, map[string]bool, string) {
	candidates := make(map[string]surgeGroupCandidate)
	var order []string

	for _, group := range groups {
		safeName, ok := groupNameMap[group.Name]
		if !ok {
			continue
		}
		candidate := surgeGroupCandidate{
			name:      safeName,
			groupType: mapSurgeGroupType(group.Type),
			params:    surgeGroupParams(group),
		}

		seenMembers := make(map[string]bool)
		for _, rawMember := range group.Proxies {
			member := strings.TrimSpace(rawMember)
			if member == "" {
				continue
			}
			if safeProxy, ok := proxyNameMap[member]; ok {
				appendUniqueSurgeGroupMember(&candidate, surgeGroupMember{name: safeProxy}, seenMembers)
				continue
			}
			if safeGroup, ok := groupNameMap[member]; ok {
				appendUniqueSurgeGroupMember(&candidate, surgeGroupMember{name: safeGroup, isGroup: true}, seenMembers)
				continue
			}
			if builtInPolicy, ok := surgeBuiltInPolicy(member); ok {
				appendUniqueSurgeGroupMember(&candidate, surgeGroupMember{name: builtInPolicy}, seenMembers)
			}
		}

		candidates[safeName] = candidate
		order = append(order, safeName)
	}

	validCache := make(map[string]bool)
	visiting := make(map[string]bool)
	var isValidGroup func(string) bool
	isValidGroup = func(name string) bool {
		if cached, ok := validCache[name]; ok {
			return cached
		}
		if visiting[name] {
			return false
		}
		candidate, ok := candidates[name]
		if !ok {
			return false
		}
		visiting[name] = true
		defer delete(visiting, name)

		for _, member := range candidate.members {
			if !member.isGroup || isValidGroup(member.name) {
				validCache[name] = true
				return true
			}
		}
		validCache[name] = false
		return false
	}

	emittedGroups := make(map[string]bool)
	var lines []string
	firstPolicy := ""

	for _, name := range order {
		if !isValidGroup(name) {
			continue
		}
		candidate := candidates[name]
		var members []string
		seenMembers := make(map[string]bool)
		for _, member := range candidate.members {
			if member.isGroup && !isValidGroup(member.name) {
				continue
			}
			if seenMembers[member.name] {
				continue
			}
			seenMembers[member.name] = true
			members = append(members, member.name)
		}
		if len(members) == 0 {
			continue
		}

		lineParts := append([]string{candidate.name + " = " + candidate.groupType}, members...)
		lineParts = append(lineParts, candidate.params...)
		lines = append(lines, strings.Join(lineParts, ","))
		emittedGroups[candidate.name] = true
		if firstPolicy == "" {
			firstPolicy = candidate.name
		}
	}

	if len(lines) == 0 {
		defaultGroupName := uniqueSurgeName("PROXY", usedNames)
		lineParts := append([]string{defaultGroupName + " = select"}, proxyNames...)
		lines = append(lines, strings.Join(lineParts, ","))
		emittedGroups[defaultGroupName] = true
		firstPolicy = defaultGroupName
	}

	return lines, emittedGroups, firstPolicy
}

func appendUniqueSurgeGroupMember(candidate *surgeGroupCandidate, member surgeGroupMember, seen map[string]bool) {
	if seen[member.name] {
		return
	}
	seen[member.name] = true
	candidate.members = append(candidate.members, member)
}

func mapSurgeGroupType(groupType string) string {
	switch strings.ToLower(strings.TrimSpace(groupType)) {
	case "url-test", "fallback", "load-balance":
		return strings.ToLower(strings.TrimSpace(groupType))
	default:
		return "select"
	}
}

func surgeGroupParams(group clashProxyGroupConfig) []string {
	groupType := mapSurgeGroupType(group.Type)
	if groupType != "url-test" && groupType != "fallback" {
		return nil
	}

	url := firstNonEmpty(valueAsString(group.URL), surgeDefaultTestURL)
	interval := firstNonEmpty(valueAsString(group.Interval), surgeDefaultInterval)
	params := []string{"url=" + cleanSurgeValue(url), "interval=" + cleanSurgeValue(interval)}
	if timeout := valueAsString(group.Timeout); timeout != "" {
		params = append(params, "timeout="+cleanSurgeValue(timeout))
	}
	if tolerance := valueAsString(group.Tolerance); tolerance != "" && groupType == "url-test" {
		params = append(params, "tolerance="+cleanSurgeValue(tolerance))
	}
	return params
}

func surgeRuleLines(rules []string, proxyNameMap, groupNameMap map[string]string, emittedGroups map[string]bool, fallbackPolicy string) []string {
	var lines []string
	for _, rawRule := range rules {
		line, ok := surgeRuleLine(rawRule, proxyNameMap, groupNameMap, emittedGroups, fallbackPolicy)
		if ok {
			lines = append(lines, line)
		}
	}

	if len(lines) == 0 {
		lines = append(lines, "FINAL,"+fallbackPolicy)
	}
	return lines
}

func surgeRuleLine(rawRule string, proxyNameMap, groupNameMap map[string]string, emittedGroups map[string]bool, fallbackPolicy string) (string, bool) {
	rule := strings.TrimSpace(rawRule)
	if rule == "" || strings.HasPrefix(rule, "#") {
		return "", false
	}

	parts := strings.Split(rule, ",")
	for i := range parts {
		parts[i] = strings.TrimSpace(parts[i])
	}
	if len(parts) < 2 {
		return "", false
	}

	ruleType := strings.ToUpper(parts[0])
	if ruleType == "MATCH" {
		target := strings.Join(parts[1:], ",")
		return "FINAL," + mapSurgePolicy(target, proxyNameMap, groupNameMap, emittedGroups, fallbackPolicy), true
	}

	targetStart := 2
	if len(parts) <= targetStart {
		return "", false
	}

	targetEnd := len(parts) - 1
	suffix := ""
	if strings.EqualFold(parts[targetEnd], "no-resolve") {
		suffix = parts[targetEnd]
		targetEnd--
	}
	if targetEnd < targetStart {
		return "", false
	}

	prefix := append([]string{}, parts[:targetStart]...)
	target := strings.Join(parts[targetStart:targetEnd+1], ",")
	converted := append(prefix, mapSurgePolicy(target, proxyNameMap, groupNameMap, emittedGroups, fallbackPolicy))
	if suffix != "" {
		converted = append(converted, suffix)
	}
	return strings.Join(converted, ","), true
}

func mapSurgePolicy(policy string, proxyNameMap, groupNameMap map[string]string, emittedGroups map[string]bool, fallbackPolicy string) string {
	policy = strings.TrimSpace(policy)
	if safeGroup, ok := groupNameMap[policy]; ok && emittedGroups[safeGroup] {
		return safeGroup
	}
	if safeProxy, ok := proxyNameMap[policy]; ok {
		return safeProxy
	}
	if builtInPolicy, ok := surgeBuiltInPolicy(policy); ok {
		return builtInPolicy
	}
	safePolicy := sanitizeSurgeName(policy)
	if emittedGroups[safePolicy] {
		return safePolicy
	}
	return fallbackPolicy
}

func surgeBuiltInPolicy(policy string) (string, bool) {
	upper := strings.ToUpper(strings.TrimSpace(policy))
	switch upper {
	case "DIRECT", "REJECT", "REJECT-DROP", "REJECT-TINYGIF":
		return upper, true
	default:
		return "", false
	}
}

func joinSurgeLine(name, proxyType, server, port string, params ...string) string {
	parts := []string{name + " = " + proxyType, cleanSurgeValue(server), cleanSurgeValue(port)}
	parts = append(parts, params...)
	return strings.Join(parts, ",")
}

func uniqueSurgeName(rawName string, used map[string]bool) string {
	name := sanitizeSurgeName(rawName)
	if name == "" {
		name = "Proxy"
	}
	base := name
	for i := 2; used[name]; i++ {
		name = fmt.Sprintf("%s %d", base, i)
	}
	used[name] = true
	return name
}

func sanitizeSurgeName(name string) string {
	replacer := strings.NewReplacer(
		",", "，",
		"\r", " ",
		"\n", " ",
		"=", "-",
	)
	return strings.TrimSpace(replacer.Replace(name))
}

func cleanSurgeValue(value string) string {
	replacer := strings.NewReplacer("\r", " ", "\n", " ")
	return strings.TrimSpace(replacer.Replace(value))
}
